import { type ScenarioData } from './types'

export const cucumberMint5: ScenarioData = {
  id: 'cucumber-mint-5', brand: 'Cucumber Mint', category: 'Personal Care', title: 'Competitive Market Positioning', description: 'Share gains vs natural skincare competitors', date: '2026-05-10', velocityScore: 7.2, sentimentScore: 76, sparklineData: [4, 4, 5, 5, 6, 6, 7],
  signals: [{ id: 'sig-1', name: 'Market Share', icon: 'flame', velocity: 7.2, sentiment: 76, trend: 'rising' }],
  initialLayout: [
    { columns: 3, cells: [{ id: '', type: 'progress-bar', status: 'ready', title: 'Trend', subtitle: "Where it's going", data: { type: 'trend', sparklineData: [4, 4, 5, 5, 6, 6, 7], color: '#3b82f6' } }, { id: '', type: 'progress-bar', status: 'ready', title: 'Strength', subtitle: 'Signal power', data: { type: 'strength', value: 7.2, max: 10, color: '#3b82f6' } }, { id: '', type: 'progress-bar', status: 'ready', title: 'Trust', subtitle: 'Source validity', data: { type: 'trust', value: 76, max: 100, color: '#f97316' } }] },
    { columns: 1, cells: [{ id: '', type: 'signal-sources', status: 'ready', title: 'Signal sources', subtitle: '', data: { total: '4,123 data points across 32 verified channels', pillars: [{ id: 'market', icon: 'TrendingUp', label: 'Market Share', value: '40%', sparklineData: [2, 3, 4, 5, 6, 7, 8], subtext: 'Competitive positioning gaining', color: 'blue' }, { id: 'brand', icon: 'Radio', label: 'Brand Mentions', value: '35%', sparklineData: [3, 4, 5, 6, 7, 8, 9], subtext: 'Social & media coverage growing', color: 'emerald' }, { id: 'research', icon: 'Search', label: 'Consumer Research', value: '25%', sparklineData: [4, 5, 6, 7, 8, 9, 10], subtext: 'Market analysis consistent', color: 'purple' }] } }] },
    { columns: 3, cells: [{ id: '', type: 'narrative', status: 'ready', title: 'Executive Summary', subtitle: '', data: 'Cucumber Mint gaining market share in natural skincare with competitive pricing. Strong positioning around natural ingredients and sustainability outperforming competitor growth.' }, { id: '', type: 'narrative', status: 'ready', title: 'Business Implications', subtitle: '', data: '• Competitive advantage built on authentic natural positioning\n\n• Sustainability story resonates with premium segments\n\n• Market expansion opportunity as category grows' }, { id: '', type: 'narrative', status: 'ready', title: 'Action Recommendations', subtitle: '', data: '• Double down on sustainability narrative in communications\n\n• Monitor competitor moves and innovation pipeline\n\n• Build awareness in under-penetrated markets\n\n• Develop premium tier products for ultra-premium segment\n\n___BUTTON___Generate Ideas___POWERED_BY_Innov8___' }] }
  ],
  chartData: { 'Monthly Revenue': [{ date: '2024-01-01', volume: 380, sentiment: 71 }, { date: '2024-02-01', volume: 450, sentiment: 74 }, { date: '2024-03-01', volume: 540, sentiment: 79 }] },
  narratives: { 'Competitive Market Positioning': 'The brand is successfully differentiated through natural ingredients and sustainable practices.' }
}
